@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@baseurl = http://{{host}}/api
@contentType = application/json
@createdAt = {{$datetime iso8601}}
@username = simulator
@password = super_safe!

###
POST {{baseurl}}/register?latest=2000
Content-Type: application/json
Connection: close
Authorization: Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh

{
    "username": "{{username}}2",
    "email" : "{{username}}2@test.dk",
    "pwd": "foo"
}
###
POST {{baseurl}}/register?latest=2000
Content-Type: application/json
Connection: close
Authorization: Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh

{
    "username": "b2",
    "email" : "b@test.dk",
    "pwd": "foo"
}


###

GET {{baseurl}}/latest
Authorization: Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh

###

GET http://159.69.213.182:9000/api/latest
Authorization: Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh

###

POST {{baseurl}}/msgs/{{username}}?latest=2
Content-Type: application/json
Connection: close
Authorization: Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh

{
    "content": "Blub!"
}
###
get {{baseurl}}/msgs?latest=2&no=33
Content-Type: application/json
Connection: close
Authorization: Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh

###
GET {{baseurl}}/msgs/{{username}}?latest=3
Content-Type: application/json
Authorization: Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh



###

GET {{baseurl}}/fllws/{{username}}?latest=12
Authorization: Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh

###

POST {{baseurl}}/fllws/{{username}}?latest=7
Content-Type: application/json
Connection: "close"
Authorization: Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh

{
    "follow": "b"
}

###

POST {{baseurl}}/fllws/{{username}}?latest=10
Content-Type: application/json
Connection: close
Authorization: Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh

{
    "unfollow": "b"
}
