[tool.poetry]
name = "minit"
version = "0.0.1"
description = "MiniTwitter for DevOps"
authors = ["p"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
Flask = "^3.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
