version: '3'
services:
  minitwizzy:
    container_name: minitwizzy-live
    restart: unless-stopped
    image: ghcr.io/patnei/minitwizzy:latest
    network_mode: service:twizzy-tailscale
    environment:
      - DB_ENV=${DB_PATH}
    volumes:
      - minitwizzy:${DB_PATH}
    
  twizzy-tailscale:
    image: tailscale/tailscale:unstable-v1.61.61
    container_name: ts-minitwizzy
    hostname: minitwizzy
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_SERVE_CONFIG=/config/twizzy.json
    volumes:
      - ${PWD}/config:/config
      - minitwizzy:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    ports:
      - 8000:3000
    dns:
      - 9.9.9.9
    restart: unless-stopped

volumes:
  minitwizzy: