version: '3'
services:
  minitwizzy:
    container_name: minitwizzy-live
    restart: unless-stopped
    image: ghcr.io/patnei/minitwizzy:latest
    environment:
      - DB_ENV=${DB_PATH}
    volumes:
      - minitwizzy:${DB_PATH}
    ports:
      - 9000:3000

volumes:
  minitwizzy: