version: '3'
services:
  minitwizzy:
    container_name: minitwizzy
    build:
      dockerfile: dockerfiles/dockerfile
      context: ../
    image: ghcr.io/patnei/minitwizzy:latest  ## goes to local registry