version: '3'
services:
  minitwizzy:
    container_name: minitwizzy-live
    restart: unless-stopped
    build:
      dockerfile: dockerfiles/dockerfile
      context: ../
    network_mode: service:twizzy-tailscale
    environment:
      - DB_ENV=${DB_PATH}
    volumes:
      - minitwizzy:/${DB_PATH}
    
  twizzy-tailscale:
    image: tailscale/tailscale:latest
    container_name: ts-minitwizzy
    hostname: minitwizzy
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_SERVE_CONFIG=/config/twizzy.json
    volumes:
      - ${PWD}/config:/config
      - minitwizzy:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    dns:
      - 9.9.9.9
    restart: unless-stopped

volumes:
  minitwizzy: