FROM oven/bun

WORKDIR /app

COPY package.json .
COPY bun.lockb .

RUN bun install

COPY src src
COPY tsconfig.json .
COPY drizzle.config.ts drizzle.config.ts

ENV NODE_ENV production
RUN bun run generate
RUN bun run migrate
RUN bun run seed
RUN bun run build
EXPOSE 3000
CMD ["bun","run","index.js"]
