FROM node:21-slim

WORKDIR /app

RUN npm -g install bun

COPY package.json .

RUN bun install

COPY src src
COPY tsconfig.json .
COPY drizzle.config.ts drizzle.config.ts

ENV NODE_ENV=production
ENV DB_ENV=/mnt/minitwit.db
RUN touch ${DB_ENV}
RUN npm run generate
RUN bun run migrate
RUN bun seed
RUN bun run build
EXPOSE 3000
CMD ["bun","run","index.js"]
