@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@baseurl = http://{{host}}
@contentType = application/json
@createdAt = {{$datetime iso8601}}
@username = simulator
@password = super_safe!

###
POST {{baseurl}}/register?latest=1337
Content-Type: application/json
Connection: "close"
Authorization: "Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh"

{
    "username": "test5",
    "email" : "test5@test.dk",
    "pwd": "foo"
}

###

GET {{baseurl}}/latest

###

POST {{baseurl}}/msgs/{{username}}?latest=2
Content-Type: application/json
Connection: "close"
Authorization: "Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh"

{
    "content": "Blub!"
}

GET {{baseurl}}/latest

###

POST {{baseurl}}/fllws/{{username}}?latest=7
Content-Type: application/json
Connection: "close"
Authorization: "Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh"

{
    "follow": "b"
}

###

POST {{baseurl}}/fllws/{{username}}?latest=10
Content-Type: application/json
Connection: "close"
Authorization: "Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh"

{
    "unfollow": "b"
}
